### ISSUE TITLE
Create a formatter for StringID

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#102]
Probably best if you create a formatter for this as well.
I'll see if I can create a default formatter to work with rsl::format that uses the operator<< overload for ostream

_Originally posted by @RisingLiberty in https://github.com/New-Creta/Rex/pull/79#discussion_r1186687112_

**Comment by RisingLiberty** [comment]
code in rsl for the default formatter:
template <typename T, typename Char = char, typename Enable = void>
struct formatter
{
  auto parse(format_parse_context& ctx) const -> decltype(ctx.begin()) // NOLINT(readability-convert-member-functions-to-static)
  {
    return ctx.begin();
  }

  template <typename FormatContext>
  auto format(const T& val, FormatContext& ctx) -> decltype(ctx.out())
  {
    rsl::stringstream ss;
    ss << val;
    return format_to(ctx.out(), "{}", ss.view());
  }
};

found in rex_std\include\rex_std\internal\format\core.h
commit hash: 06200225117b215fac45e88357453a3c5c1d75c7
