### ISSUE TITLE
Profile if memset of 0 is faster over an assignment of string data and the 0 terminator

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#103]
I'm not sure if it's faster, it'll probably depend on the length of the string.
it'll also depend if this first access to the memory, on first access and if the memory used for this was on a previous unused page, the OS needs to actually initialize the page, that might be what you've seen before.

I'd like to see this profiled in possible though, if you copy everything first and then add a null termination char at the end, I dont' see how this would be slower over what's implemented here

_Originally posted by @RisingLiberty in https://github.com/New-Creta/Rex/pull/79#discussion_r1186900799_

**Comment by RisingLiberty** [comment]
testing with small, medium and big strings.
1 million iterations, testing setting entire buff to 0 and then copying over vs copying over and setting final char to 0
results:

processing end zero first
----------------------------
full zero time: 77.3962 ms
end zero time: 75.1279 ms

full zero time: 78.2053 ms
end zero time: 76.2983 ms

full zero time: 77.8897 ms
end zero time: 75.7706 ms

processing full zero first
----------------------------
full zero time: 79.6391 ms
end zero time: 76.2169 ms

full zero time: 77.8624 ms
end zero time: 75.0272 ms

full zero time: 77.4033 ms
end zero time: 74.7946 ms

setting the entire array to 0 and then copying over is **always** slower than only setting the last character.
the last character might still be in a cpu register which could explain why this is faster.

@Dyronix please change code in stringid accordingly

**Comment by Dyronix** [comment]
I still think it's weird.
The copy of the data always needs to happen in both cases.
So the comparison is between clearing a buffer to 0 or going to address x and setting a value
I thought jumping to an address was slower than clearing memory but I guess I was wrong
