### ISSUE TITLE
Figure out a design on how to mark invalid objects

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#106]
I wonder if we should mark ctor that are meant to only be used with assert in a special way, what do you think?

_Originally posted by @RisingLiberty in https://github.com/New-Creta/Rex/pull/72#discussion_r1186694906_

**Comment by RisingLiberty** [comment]
it can be as simple as
template <typename T>
T invalid_object()
{
  return *reinterpret_cast<T*>(nullptr);
}

**Comment by RisingLiberty** [comment]
the above results in an error.
I came up with the following which doesn't error

```
std::array<int, 4> invalid_obj_buffer = { 0x0000DEAD, 0x0000DEAD, 0x0000DEAD, 0x0000DEAD };

struct Test
{
  int x;
};

template <typename T>
T invalid_obj()
{
  std::array<char, sizeof(T)> buff;
  size_t num_to_copy = (std::min)(sizeof(T), sizeof(invalid_obj_buffer));
  memcpy(buff.data(), invalid_obj_buffer.data(), num_to_copy);
  return *reinterpret_cast<T*>(buff.data());
}
```

**Comment by Dyronix** [comment]
Did you create 4 elements to be 16 bytes aligned?

**Comment by RisingLiberty** [comment]
pr has been made
https://github.com/New-Creta/Rex/pull/165
