### ISSUE TITLE
App shouldn't pause when resizing is happening

### ISSUE THREAD

**Issue by RisingLiberty** [New-Creta/Rex#109]

**Comment by RisingLiberty** [comment]
or at least it should be behind a config

**Comment by Dyronix** [comment]
Rendering should at least be paused we don't want to recreate a swapchain continuously while we are dragging the screen. this should only happen when we stop resizing

**Comment by RisingLiberty** [comment]
PR has been made https://github.com/New-Creta/Rex/pull/166
