### ISSUE TITLE
Compile time string id

### ISSUE THREAD

**Issue by RisingLiberty** [New-Creta/Rex#127]
A string id who's hash is generated at compile time
They could be called StringViewID. They don't get added to the hash table, as that would be impossible at compile time, but they hold a string view and a hash internally.
This makes them very useful for string literals.

**Comment by Dyronix** [comment]
Yes I was wondering if this might be possible as a StringID is basically an integer so in theory, we could use a switch on a string

**Comment by RisingLiberty** [comment]
later I had a different idea where a string view id is actually not needed.
StringID becomes a constexpr object, everything in it can be evaluated at compile time.
that way, I don't think you need a string view id and you can still do the following

switch(my_string_id)
{
case "some_val"_sid: // something
case "some_other_val"_sid: //something else
};

sorry, I thought about this later and thought I shared it here
