### ISSUE TITLE
GenerateSettings should include PlatformType

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#144]
To be able to exclude files / folders from the generation we need to add those files / folder to the following list SourceFilesExcludeRegex
within the constructor of a project.

For instance:
    // Only needs to happen on Windows
    SourceFilesExcludeRegex.Add("unix/*");

but, since there is no way to check the platform within the ctor of a project we cannot check if we need to add those to the filter or not. A similar approach was already taken care of for the OpenGL and DirectX libraries where we added GraphicsAPI to the generation settings. It might but use full to add the Platform here as well.

**Comment by RisingLiberty** [comment]
I actually don't think this is needed in the generate settings, that's what configuration is for
