### ISSUE TITLE
We are not able to convert rsl::string_view into rex::DebugString

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#145]
Create a hash table ->
rex::unordered_map<rex::DebugString, MyObject>

Try and find an element where key is a rsl::string_view ->
auto found = m_objects.find(key);
    return found == m_objects.end() 
          ? nullptr 
          : found->value;

Error occurs ->
cannot convert argument 1 from 'const K' to 'const rsl::v1::basic_string<rsl::v1::char8,rsl::v1::char_traits<rsl::v1::char8>,rex::v1::DebugAllocator<rex::UntrackedAllocator>> &'
with
[
    Key=rex::DebugString
]
    and
[
    K=rsl::v1::string_view
]

**Comment by RisingLiberty** [comment]
the bug isn't really that you can't convert a string view to a string, that is possible but is explicit and is so by design.
the bug is that you can't search in a hashtable using strings as keys and the search type being a string view

**Comment by RisingLiberty** [comment]
a PR has been made https://github.com/New-Creta/Rex/pull/176
