### ISSUE TITLE
naming code guidelines aren't followed in this file.

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#196]
naming code guidelines aren't followed in this file.
some make sense not to follow (eg. a_formatter) but I'd recommend to use them on the members inside these classes

_Originally posted by @RisingLiberty in https://github.com/New-Creta/Rex/pull/178#discussion_r1212414184_

**Comment by RisingLiberty** [comment]
I don't think we need this, it'll only add maintenance
