### ISSUE TITLE
Make path.h and path.cpp consistant with how we tackle platform/architecture specific code

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#239]
We have a renderer.h and a dx_renderer.cpp and gl_renderer.cpp the source files implement the API of the header file which is within common space. If we are on Windows the filesystem/win is included within the engine project so this will be the implementation we use within the setup configuration. This means if a different platform is loaded only another sourcefile has to implemented with the given API within path.h

**Comment by RisingLiberty** [comment]
fixed it in https://github.com/New-Creta/Rex/pull/241
