### ISSUE TITLE
Transpose DX matrices

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#259]
Find if there is a more performant solution for DX materices vs GL matrices as one is row major and the other one column major and we would have to transpose each time when using DX API

**Comment by RisingLiberty** [comment]
https://gamedev.stackexchange.com/questions/153816/why-do-these-directxmath-functions-seem-like-they-return-column-major-matrics
https://learn.microsoft.com/en-us/windows/win32/dxmath/pg-xnamath-getting-started?redirectedfrom=MSDN#matrix_convention

**Comment by RisingLiberty** [comment]
Doesn't look like this is easily possible unless we change the major in the shaders which I don't think we should do
