### ISSUE TITLE
Split up different tests in _rex.py

### ISSUE THREAD

**Issue by RisingLiberty** [New-Creta/Rex#272]
As you have split the setup, generate, build. run and test I would also split up test, autotest and fuzzy test. This way you cannot give it any wrong arguments and you don't need the desription ( applies to ... testing )

_Originally posted by @Dyronix in https://github.com/New-Creta/Rex/pull/225#discussion_r1434234489_

**Comment by Dyronix** [comment]
Update documentation if this is finished

**Comment by RisingLiberty** [comment]
A review has been made
