### ISSUE TITLE
Add a file version to the "default_config.json"

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#306]
When a configuration was generated with a specific a "default_config.json" file, and you alter the HEAD in git issues for generating a new solution might arise due to the cached generation file being present but different options might be referenced within this cached file. A solution to this problem might be to add a version to the "cached_config.json" file. When the version has a mismatch the default-config file has to be used again instead of the cached file.

**Comment by RisingLiberty** [comment]
this is now in main
