### ISSUE TITLE
changing folder structure for platforms

### ISSUE THREAD

**Issue by RisingLiberty** [New-Creta/Rex#81]
We need a cpp and header file for each graphics API we tend to support (eg. opengl_renderer.cpp, opengl_renderer.h)
in the API's root include folder (or wherever makes sense) a new header file gets added.

at the moment the renderer interface sits in RexRendererCode and Windows implementation are in RexWindows.
we want to move render code into RexRender (drop the"Core") and split implementation into folders instead.

The same strategy should be used for RexWindows going into RexEngine

**Comment by Dyronix** [comment]
There was no mention of renaming RexRendererCore to RexRender in our discussion, which I also think shouldn't happen. Libraries IMO should not be verb, always represented as a noun. So I can always rename it to RexRenderer to find a common ground

**Comment by RisingLiberty** [comment]
it was a typo on my part.
RexRenderer is fine

**Comment by RisingLiberty** [comment]
will review this when directx branch is in main

**Comment by RisingLiberty** [comment]
this is an issue because RexRenderer would have a dependency on RexEngine, but RexEngine would have to spawn the renderer, meaning it'd have a dependency on RexRenderer causing a circular dependency.

**Comment by RisingLiberty** [comment]
so unless we'd merge the RexEngine with RexRenderer or come up with a third Project which would have a dependency on RexEngine and RexRenderer (like RexWindows, although, I'd go for a cross platfrom one eg RexPlatform) this is not possible

**Comment by RisingLiberty** [comment]
Another solution to this would be if the cross platform engine layer doesn't spawn the renderer but the platform specific project handles this. This is what happens now. We'll stick with this for now and change it when we need to in the future
