### ISSUE TITLE
_test.py -clang_tidy iteration speed is really slow

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#85]
When trying to test if local changes are ready to be pushed to the server we run several tests first to check if nothing broke. 
One of these tests is _test.py -clang_tidy

clang tidy will check all available compiler databases to be able to perform it's checks while this is a good thing we don't need to check the entire codebase every time we make a small change. This is slowing down iterations speed dramatically. 

It might be useful to figure out a solution to only test the files you recently change or test a specific library within the code base.
We already have such a system in place for pre-push event but this is using git maybe we can extract some of the functionality within that system and apply it here.

**Comment by RisingLiberty** [comment]
fixed in https://github.com/New-Creta/Rex/pull/80
