### ISSUE TITLE
Cancel _test.py -clang_tidy

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#86]
Canceling clang tidy run either doesn't fully close down and you are forced to use the task manager on your local machine or it takes a very long time for the script to finish.

**Comment by RisingLiberty** [comment]
I haven't encountered this myself, Windows spawns it as a subprocess of the terminal, using Ctrl + C cancels everything, including clang-tidy

**Comment by Dyronix** [comment]
I'll investigate if the issue would be resolved once I tested the lesser core solution
