### ISSUE TITLE
Adapter - ComObject pattern

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#96]
The Adapter class is created to store information about the current adapter that is being used ( aka the GPU) however, the design that has been used within DX is quite complex and introduces multiple inheritance while there is nothing wrong with multiple inheritance we might want to look into a different approach of handling these adaptors.

**Comment by RisingLiberty** [comment]
will review this when directx branch is in main

**Comment by RisingLiberty** [comment]
https://github.com/New-Creta/Rex/pull/129
