### ISSUE TITLE
Option to reduce the available core clang-tidy uses

### ISSUE THREAD

**Issue by Dyronix** [New-Creta/Rex#97]
Clang tidy enforces all cores to compile the project, this hooks all resources from the device it's running on leaving no room for other applications to execute logic.
An option to reduce the amount of cores used by clang tidy would help

**Comment by RisingLiberty** [comment]
this has been possible since rexpy version 0.1.16

**Comment by Dyronix** [comment]
Could you tell me how I set this up?

**Comment by RisingLiberty** [comment]
when running _test.py use the argument "-single_threaded"
